Vue.component('pane',{
    name:'pane',
    template:'\
    <div class="pane" v-show="show">\
    <slot></slot>\
    </div>',
    props:{
        name:{
            type:String
        },
        label:{
            type:String,
            default:''
        },
        closeable:{
            type:[Boolean],
            default:false
        }
    },
    data:function(){
        return {
            show:true
        }
    },
    methods:{
        updataNav:function(){
            this.$parent.updateNav();
        }
    },
    watch:{
        label:function(){
            this.updataNav();
        }
    },
    mounted:function(){
        console.log(this.closeable);
        //console.log(this.label);
        this.updataNav();
    },
    beforeDestroy:function(){
        console.log("销毁了");
    }
})